qca-wifi-host-cmn: Add void keyword to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing `void` is triggering
the Wstrict-prototype warns. Explicitly add the `void` keyword to
satisfy the compiler.

This fixes the following warnings:

drivers/staging/qca-wifi-host-cmn/hif/src/ce/ce_service.c:2742:34:
error: a function declaration without a prototype is deprecated in all
versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void
drivers/staging/qca-wifi-host-cmn/hif/src/ce/ce_service_srng.c:864:34:
error: a function declaration without a prototype is deprecated in all
versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void
drivers/staging/qca-wifi-host-cmn/target_if/core/src/target_if_main.c:81:40:
error: a function declaration without a prototype is deprecated in all
versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void
drivers/staging/qca-wifi-host-cmn/wlan_cfg/wlan_cfg.c:292:49:
error: a function declaration without a prototype is deprecated in all
versions of C [-Werror,-Wstrict-prototypes]
struct wlan_cfg_dp_soc_ctxt *wlan_cfg_soc_attach()
                                                ^
                                                 void

Change-Id: Ifd95b57d19a25f0932e5de8ec4de2f2c1e7e1259
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>